services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sypets\SypetsExamplePlugincacheexpiration\:
    resource: '../Classes/*'

  Sypets\SypetsExamplePlugincacheexpiration\EventListener\PageCacheEventListener:
    public: true
    tags:
      - name: event.listener
        identifier: 'pageCacheEventListener'
        event: TYPO3\CMS\Frontend\Event\SetPageCacheEvent

